query_example = (
    'Write a report to explain and summarize the impact of quantum computing '
    'on modern cryptography. Include diagrams showing how quantum algorithms'
    " like Shor's algorithm can break RSA encryption, and a figure showing"
    " the difference in runtime between Shor's algorithm and a classical"
    ' algorithm for factoring prime numbers. Compare the timeline of quantum'
    ' computing development with the evolution of post-quantum cryptographic'
    ' methods. End with a visual representation of which current encryption'
    ' methods are most vulnerable to quantum attacks.'
)

task_response_example = (
    '{\n'
    '  "subtasks": [\n'
    '    {\n'
    '      "type": "text",\n'
    '      "description": "Introduction to quantum computing and cryptography",\n'
    '      "prompt": "Write a clear introduction explaining what quantum'
    ' computing is and its relationship to modern cryptography. Define key'
    ' terms and explain why this topic is important for cybersecurity.",\n'
    '      "order": 1\n'
    '    },\n'
    '    {\n'
    '      "type": "text",\n'
    '      "description": "Overview of traditional cryptographic methods",\n'
    '      "prompt": "Provide a concise overview of traditional cryptographic'
    " methods like RSA, explaining how they work and why they're currently"
    ' considered secure. Focus on the mathematical problems (like prime'
    ' factorization) that make them difficult to break with classical computers.",\n'
    '      "order": 2\n'
    '    },\n'
    '    {\n'
    '      "type": "image",\n'
    '      "description": "Diagram of RSA encryption",\n'
    '      "prompt": "Create a clear, professional diagram showing how RSA'
    ' encryption works, including key generation, encryption, and decryption'
    ' processes. Use a flowchart style with mathematical notation where'
    ' appropriate.",\n'
    '      "alt_text": "Flowchart diagram showing the process of RSA'
    ' encryption and decryption including key generation, encryption with'
    ' public key, and decryption with private key.",\n'
    '      "caption": "Figure 1: Traditional RSA encryption process relying'
    ' on the difficulty of prime factorization",\n'
    '      "order": 3\n'
    '    },\n'
    '    {\n'
    '      "type": "text",\n'
    '      "description": "Explanation of quantum computing threats",\n'
    '      "prompt": "Explain how quantum computers fundamentally change the'
    ' security landscape. Describe qubits, superposition, and quantum'
    ' parallelism, and how these enable quantum computers to solve certain'
    ' problems exponentially faster than classical computers.",\n'
    '      "order": 4\n'
    '    },\n'
    '    {\n'
    '      "type": "text",\n'
    '      "description": "Detailed explanation of Shor\'s algorithm",\n'
    '      "prompt": "Provide a detailed yet accessible explanation of Shor\'s'
    ' algorithm, how it works to factor large numbers efficiently, and why'
    ' this poses a direct threat to RSA encryption and similar cryptographic'
    ' systems.",\n'
    '      "order": 5\n'
    '    },\n'
    '    {\n'
    '      "type": "image",\n'
    '      "description": "Diagram of Shor\'s algorithm breaking RSA",\n'
    '      "prompt": "Create a technical diagram showing how Shor\'s algorithm'
    ' works to break RSA encryption. Include quantum circuits and the key'
    ' steps that enable efficient factorization of large numbers.",\n'
    '      "alt_text": "Technical diagram illustrating how Shor\'s algorithm'
    ' uses quantum circuits to efficiently factor large numbers and break RSA'
    ' encryption.",\n'
    '      "caption": "Figure 2: How Shor\'s algorithm leverages quantum'
    ' properties to break RSA encryption",\n'
    '      "order": 6\n'
    '    },\n'
    '    {\n'
    '      "type": "image",\n'
    '      "description": "Runtime comparison chart",\n'
    '      "prompt": "Create a logarithmic graph comparing the runtime'
    ' complexity of classical factoring algorithms (like the General Number'
    " Field Sieve) versus Shor's quantum algorithm as the bit-size of the"
    ' number to be factored increases. Show how classical algorithms grow'
    ' exponentially while Shor\'s algorithm grows polynomially.",\n'
    '      "alt_text": "Logarithmic graph comparing the exponential growth in'
    ' runtime for classical factoring algorithms versus the polynomial growth'
    ' for Shor\'s quantum algorithm as number size increases.",\n'
    '      "caption": "Figure 3: Runtime comparison between classical'
    ' factoring algorithms and Shor\'s quantum algorithm",\n'
    '      "order": 7\n'
    '    },\n'
    '    {\n'
    '      "type": "text",\n'
    '      "description": "Impact on specific cryptographic systems",\n'
    '      "prompt": "Analyze the specific impact of quantum computing on'
    ' different cryptographic systems beyond RSA, including ECC (Elliptic'
    ' Curve Cryptography), symmetric key algorithms like AES, and hash'
    ' functions. Explain which are most vulnerable and why.",\n'
    '      "order": 8\n'
    '    },\n'
    '    {\n'
    '      "type": "text",\n'
    '      "description": "Timeline of quantum computing development",\n'
    '      "prompt": "Present a detailed narrative comparing the timeline of'
    ' quantum computing advancements (theoretical breakthroughs, hardware'
    ' improvements, qubit counts, error rates) with the parallel development'
    ' of post-quantum cryptographic methods from the 1990s to present day.",\n'
    '      "order": 9\n'
    '    },\n'
    '    {\n'
    '      "type": "image",\n'
    '      "description": "Comparative timeline visualization",\n'
    '      "prompt": "Create a dual timeline visualization showing quantum'
    ' computing milestones on the top half (including theoretical'
    ' breakthroughs, hardware developments, and key demonstrations) and'
    ' post-quantum cryptography developments on the bottom half (including'
    ' proposals, standardization efforts, and adoption) from the 1990s to'
    ' present day. Use different colors to distinguish between theoretical'
    ' advances and practical implementations.",\n'
    '      "alt_text": "Dual timeline comparing quantum computing milestones'
    ' and post-quantum cryptography developments from the 1990s to present day.",\n'
    '      "caption": "Figure 4: Parallel evolution of quantum computing'
    ' capabilities and post-quantum cryptographic methods",\n'
    '      "order": 10\n'
    '    },\n'
    '    {\n'
    '      "type": "text",\n'
    '      "description": "Post-quantum cryptography overview",\n'
    '      "prompt": "Provide an overview of the main approaches to'
    ' post-quantum cryptography, including lattice-based, hash-based,'
    ' code-based, multivariate, and isogeny-based cryptography. Briefly'
    ' explain how each works and their current status in standardization'
    ' processes.",\n'
    '      "order": 11\n'
    '    },\n'
    '    {\n'
    '      "type": "image",\n'
    '      "description": "Vulnerability assessment chart",\n'
    '      "prompt": "Create a visual matrix or heat map showing which current'
    ' encryption methods are most vulnerable to quantum attacks. Include'
    ' common cryptographic systems (RSA, ECC, AES with different key sizes,'
    ' SHA-2, SHA-3, etc.) on one axis and their relative vulnerability level'
    ' on the other, using color coding from red (highly vulnerable) to green'
    ' (quantum resistant).",\n'
    '      "alt_text": "Heat map visualization showing the relative'
    ' vulnerability of different encryption methods to quantum computing'
    ' attacks, color-coded from red (highly vulnerable) to green (quantum'
    ' resistant).",\n'
    '      "caption": "Figure 5: Vulnerability assessment of current'
    ' encryption methods to quantum computing attacks",\n'
    '      "order": 12\n'
    '    },\n'
    '    {\n'
    '      "type": "text",\n'
    '      "description": "Practical recommendations and conclusion",\n'
    '      "prompt": "Conclude with practical recommendations for'
    ' organizations and systems that need to maintain long-term security.'
    ' Discuss crypto-agility, hybrid approaches, and timelines for'
    ' transitioning to post-quantum methods. Summarize the key takeaways about'
    ' the impact of quantum computing on cryptography.",\n'
    '      "order": 13\n'
    '    }\n'
    '  ]\n'
    '}'
)
