query_example = (
    'Write a report to explain and summarize the impact of quantum computing '
    'on modern cryptography. Include diagrams showing how quantum algorithms'
    " like Shor's algorithm can break RSA encryption, and a figure showing"
    " the difference in runtime between Shor's algorithm and a classical"
    ' algorithm for factoring prime numbers. Compare the timeline of quantum'
    ' computing development with the evolution of post-quantum cryptographic'
    ' methods. End with a visual representation of which current encryption'
    ' methods are most vulnerable to quantum attacks.'
)

task_response_example = (
    '{\n'
    '  "subtasks": [\n'
    '    {\n'
    '      "type": "text",\n'
    '      "description": "Introduction to quantum computing and cryptography",\n'
    '      "prompt": "Write a clear introduction explaining what quantum'
    ' computing is and its relationship to modern cryptography. Define key'
    ' terms and explain why this topic is important for cybersecurity.",\n'
    '      "order": 1\n'
    '    },\n'
    '    {\n'
    '      "type": "text",\n'
    '      "description": "Overview of traditional cryptographic methods",\n'
    '      "prompt": "Provide a concise overview of traditional cryptographic'
    " methods like RSA, explaining how they work and why they're currently"
    ' considered secure. Focus on the mathematical problems (like prime'
    ' factorization) that make them difficult to break with classical'
    ' computers.",\n'
    '      "order": 2\n'
    '    },\n'
    '    {\n'
    '      "type": "tikz",\n'
    '      "description": "Diagram of RSA encryption",\n'
    '      "prompt": "Create a precise TikZ diagram showing the RSA encryption'
    ' process. Include: 1) Key generation with prime numbers p and q,'
    ' computing n=pq and totient=(p-1)(q-1), selecting e and computing d such'
    ' that ed ≡ 1 (mod totient). 2) Encryption process with C=M^e mod n. 3)'
    ' Decryption with M=C^d mod n. Use proper mathematical notation and'
    ' organize as a flowchart with three distinct sections.",\n'
    '      "alt_text": "Flowchart diagram showing the process of RSA'
    ' encryption and decryption including key generation, encryption with'
    ' public key, and decryption with private key.",\n'
    '      "caption": "Figure 1: Traditional RSA encryption process relying'
    ' on the difficulty of prime factorization",\n'
    '      "order": 3\n'
    '    },\n'
    '    {\n'
    '      "type": "text",\n'
    '      "description": "Explanation of quantum computing threats",\n'
    '      "prompt": "Explain how quantum computers fundamentally change the'
    ' security landscape. Describe qubits, superposition, and quantum'
    ' parallelism, and how these enable quantum computers to solve certain'
    ' problems exponentially faster than classical computers.",\n'
    '      "order": 4\n'
    '    },\n'
    '    {\n'
    '      "type": "text",\n'
    '      "description": "Detailed explanation of Shor\'s algorithm",\n'
    '      "prompt": "Provide a detailed yet accessible explanation of Shor\'s'
    ' algorithm, how it works to factor large numbers efficiently, and why'
    ' this poses a direct threat to RSA encryption and similar cryptographic'
    ' systems.",\n'
    '      "order": 5\n'
    '    },\n'
    '    {\n'
    '      "type": "tikz",\n'
    '      "description": "Quantum circuit for Shor\'s algorithm",\n'
    '      "prompt": "Create a TikZ diagram of a simplified quantum circuit for'
    " Shor's algorithm. Show the two quantum registers (upper register with"
    ' control qubits and lower register with target qubits), the quantum Fourier'
    ' transform (QFT) applied to the first register, the modular exponentiation'
    ' operations, and measurement operations. Use proper quantum circuit notation'
    ' with horizontal lines for qubits and vertical/connecting lines for gates.",\n'
    '      "alt_text": "Technical diagram illustrating the quantum circuit for'
    " Shor's algorithm with two registers, quantum Fourier transform, and"
    ' measurements used to factor large numbers and break RSA encryption.",\n'
    '      "caption": "Figure 2: Quantum circuit implementation of Shor\'s algorithm",\n'
    '      "order": 6\n'
    '    },\n'
    '    {\n'
    '      "type": "tikz",\n'
    '      "description": "Runtime comparison chart",\n'
    '      "prompt": "Create a TikZ plot comparing the runtime complexity of'
    " classical factoring algorithms versus Shor's quantum algorithm. Use a"
    ' logarithmic scale y-axis (runtime) and linear x-axis (number of bits).'
    ' Plot the General Number Field Sieve complexity O(exp((64/9)^(1/3) * (log n)^(1/3)'
    " * (log log n)^(2/3))) in red and Shor's algorithm complexity O(log^3 n) in blue."
    ' Use a range of 256 to 4096 bits for RSA keys. Include a legend and properly'
    ' labeled axes with grid lines.",\n'
    '      "alt_text": "Logarithmic graph comparing the exponential growth in'
    ' runtime for classical factoring algorithms versus the polynomial growth'
    ' for Shor\'s quantum algorithm as number size increases.",\n'
    '      "caption": "Figure 3: Runtime comparison between classical'
    ' factoring algorithms and Shor\'s quantum algorithm",\n'
    '      "order": 7\n'
    '    },\n'
    '    {\n'
    '      "type": "text",\n'
    '      "description": "Impact on specific cryptographic systems",\n'
    '      "prompt": "Analyze the specific impact of quantum computing on'
    ' different cryptographic systems beyond RSA, including ECC (Elliptic'
    ' Curve Cryptography), symmetric key algorithms like AES, and hash'
    ' functions. Explain which are most vulnerable and why.",\n'
    '      "order": 8\n'
    '    },\n'
    '    {\n'
    '      "type": "text",\n'
    '      "description": "Timeline of quantum computing development",\n'
    '      "prompt": "Present a detailed narrative comparing the timeline of'
    ' quantum computing advancements (theoretical breakthroughs, hardware'
    ' improvements, qubit counts, error rates) with the parallel development'
    ' of post-quantum cryptographic methods from the 1990s to present day.",\n'
    '      "order": 9\n'
    '    },\n'
    '    {\n'
    '      "type": "image",\n'
    '      "description": "Comparative timeline visualization",\n'
    '      "prompt": "Create a dual timeline visualization showing quantum'
    ' computing milestones on the top half (including theoretical'
    ' breakthroughs, hardware developments, and key demonstrations) and'
    ' post-quantum cryptography developments on the bottom half (including'
    ' proposals, standardization efforts, and adoption) from the 1990s to'
    ' present day. Use different colors to distinguish between theoretical'
    ' advances and practical implementations.",\n'
    '      "alt_text": "Dual timeline comparing quantum computing milestones'
    ' and post-quantum cryptography developments from the 1990s to present day.",\n'
    '      "caption": "Figure 4: Parallel evolution of quantum computing'
    ' capabilities and post-quantum cryptographic methods",\n'
    '      "order": 10\n'
    '    },\n'
    '    {\n'
    '      "type": "text",\n'
    '      "description": "Post-quantum cryptography overview",\n'
    '      "prompt": "Provide an overview of the main approaches to'
    ' post-quantum cryptography, including lattice-based, hash-based,'
    ' code-based, multivariate, and isogeny-based cryptography. Briefly'
    ' explain how each works and their current status in standardization'
    ' processes.",\n'
    '      "order": 11\n'
    '    },\n'
    '    {\n'
    '      "type": "tikz",\n'
    '      "description": "Vulnerability assessment chart",\n'
    '      "prompt": "Create a TikZ heat map visualization showing the vulnerability'
    ' of different cryptographic algorithms to quantum attacks. Use a grid with'
    ' algorithms on the y-axis (RSA-2048, RSA-4096, ECC-256, ECC-384, AES-128,'
    ' AES-256, SHA-256, SHA-3, NTRU, Dilithium, Saber, etc.) and vulnerability'
    ' level on the x-axis. Use color gradient from green (resistant) to red'
    ' (vulnerable). Include a colored legend explaining the vulnerability scale'
    ' and group the algorithms by type (asymmetric, symmetric, hash functions,'
    ' post-quantum).",\n'
    '      "alt_text": "Heat map visualization showing the relative'
    ' vulnerability of different encryption methods to quantum computing'
    ' attacks, color-coded from red (highly vulnerable) to green (quantum'
    ' resistant).",\n'
    '      "caption": "Figure 5: Vulnerability assessment of current'
    ' encryption methods to quantum computing attacks",\n'
    '      "order": 12\n'
    '    },\n'
    '    {\n'
    '      "type": "text",\n'
    '      "description": "Practical recommendations and conclusion",\n'
    '      "prompt": "Conclude with practical recommendations for'
    ' organizations and systems that need to maintain long-term security.'
    ' Discuss crypto-agility, hybrid approaches, and timelines for'
    ' transitioning to post-quantum methods. Summarize the key takeaways about'
    ' the impact of quantum computing on cryptography.",\n'
    '      "order": 13\n'
    '    }\n'
    '  ]\n'
    '}'
)
