planning_prompt_template = (
    '**Task:**'
    '\n\n'
    'You are an AI assistant that plans multimodal responses including'
    ' text, images, and TikZ diagrams. '
    'Given the following user query, create a plan for a response that'
    ' uses both text and images as appropriate. '
    '\n\n'
    'Your plan should be a JSON-formatted list of subtasks, where each'
    ' subtask includes:\n'
    '- type: "text", "image", or "tikz"\n'
    '- description: what this element should contain\n'
    '- prompt: the exact prompt to use for generating this element'
    ' (for text or image)\n'
    '- order: the position of this element in the final response'
    '\n\n'
    'For images and TikZ diagrams, also include:\n'
    '- alt_text: accessibility text for the image or diagram\n'
    '- caption: optional caption to show below the image or diagram'
    '\n\n'
    '**Important:**'
    '\n\n'
    'Make sure the response flows naturally with text and images'
    ' interleaved in a logical way.'
    '\n\n'
    '**Format Constraint:**'
    '\n\n'
    '- Your entire response must consist solely of valid JSON with no'
    ' other text.\n'
    '- Return the plan as a JSON object with a "subtasks" key containing'
    ' an array of subtasks.\n'
    '- DO NOT include any additional text or formatting whatsoever.'
    '\n\n'
    '**Example:**'
    '\n\n'
    '**Example Query:**'
    '\n\n'
    '{query_example}'
    '\n\n'
    '**Example Response:**'
    '\n\n'
    '{task_response_example}'
    '\n\n'
    '**User Query:**'
    '\n\n'
    '{prompt}'
    '\n\n'
    '**Reminder:**'
    '\n\n'
    'Your only task is to output the structured JSON plan. '
    'Respond with exactly the JSON structure shown in the example,'
    ' nothing before it and nothing after it. '
    'Any text outside the JSON object will make your response unusable'
    ' for my automated pipeline.'
)


if __name__ == '__main__':
    print(planning_prompt_template, '\n\n')
